from abrir_json import Parametros

PARAMETROS = Parametros()

VALOR_RIESGO = PARAMETROS.editar_diccionario("VALOR_RIESGO")

PROBABILIDADES_DE_TRANSICION = PARAMETROS.editar_diccionario("PROBABILIDADES_DE_TRANSICION")

TASA_LLEGADA_HOSPITAL = PARAMETROS.editar_diccionario("TASA_LLEGADA_HOSPITAL")

CAMAS_POR_UNIDAD = PARAMETROS.editar_diccionario("CAMAS_POR_UNIDAD")

COSTOS_POR_UNIDAD = PARAMETROS.editar_diccionario("COSTOS_POR_UNIDAD")

COSTOS_TRASLADO = PARAMETROS.editar_diccionario("COSTOS_TRASLADO")

COSTOS_DERIVACION = PARAMETROS.editar_diccionario("COSTOS_DERIVACION")

TIEMPOS_ESPERA = PARAMETROS.editar_diccionario("TIEMPOS_ESPERA")

PARAMETROS_DISTRIBUCION_TIEMPO = PARAMETROS.editar_diccionario("DISTRIBUCION_TIEMPO")

PARAMETROS_ESTRATEGIA_PRINCIPALES = PARAMETROS.editar_diccionario("PARAMETROS_ESTRATEGIA_PRINCIPALES")
